"""Name

Revision ID: 8ea7fc317ddb
Revises: 4aac5b487801
Create Date: 2024-10-14 15:36:05.405676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea7fc317ddb'
down_revision = '4aac5b487801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
